name: my_own_grocery_app_2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  video_player: ^2.8.6
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  firebase_admin: ^0.2.0
  cloud_firestore: ^4.17.2
  provider: ^6.1.2
  firebase_ui_auth: ^1.7.0
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  google_sign_in: ^6.2.1
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/intro.mp4
    - assets/pictures/
